[2023-04-22T22:50:07.991+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:50:07.999+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:50:08.001+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:50:08.000+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:50:08.075+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:50:08.067+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:50:08.076+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:50:08.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.151 seconds
[2023-04-22T22:50:38.589+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:50:38.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:50:38.594+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:50:38.594+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:50:38.623+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:50:38.619+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:50:38.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:50:38.656+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.083 seconds
[2023-04-22T22:51:09.231+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:51:09.233+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:51:09.235+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:51:09.234+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:51:09.254+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:51:09.251+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:51:09.255+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:51:09.300+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.091 seconds
[2023-04-22T22:51:39.608+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:51:39.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:51:39.613+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:51:39.612+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:51:39.628+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:51:39.626+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:51:39.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:51:39.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.060 seconds
[2023-04-22T22:52:10.074+0000] {processor.py:153} INFO - Started process (PID=237) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:52:10.076+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:52:10.078+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:52:10.078+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:52:10.097+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:52:10.095+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:52:10.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:52:10.124+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.058 seconds
[2023-04-22T22:52:40.480+0000] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:52:40.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:52:40.488+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:52:40.487+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:52:40.510+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:52:40.508+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:52:40.510+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:52:40.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.072 seconds
[2023-04-22T22:53:10.936+0000] {processor.py:153} INFO - Started process (PID=340) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:53:10.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:53:10.940+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:53:10.940+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:53:10.970+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:53:10.968+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:53:10.971+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:53:11.003+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.073 seconds
[2023-04-22T22:53:41.183+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:53:41.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:53:41.191+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:53:41.191+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:53:41.220+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:53:41.218+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:53:41.222+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:53:41.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.075 seconds
[2023-04-22T22:54:11.375+0000] {processor.py:153} INFO - Started process (PID=441) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T22:54:11.377+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T22:54:11.379+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:54:11.379+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T22:54:11.396+0000] {logging_mixin.py:137} INFO - [2023-04-22T22:54:11.395+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from models import ARIMA
ModuleNotFoundError: No module named 'models'
[2023-04-22T22:54:11.397+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T22:54:11.425+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.057 seconds
[2023-04-22T23:03:08.967+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:03:08.984+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:03:08.989+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:03:08.989+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:03:09.035+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:03:09.027+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 7, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:03:09.037+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:03:09.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.103 seconds
[2023-04-22T23:03:39.723+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:03:39.726+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:03:39.729+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:03:39.729+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:03:39.748+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:03:39.745+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 7, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:03:39.749+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:03:39.799+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.088 seconds
[2023-04-22T23:04:10.182+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:04:10.185+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:04:10.186+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:04:10.186+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:04:10.208+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:04:10.206+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 7, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:04:10.209+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:04:10.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.076 seconds
[2023-04-22T23:04:40.748+0000] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:04:40.755+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:04:40.760+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:04:40.759+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:04:40.777+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:04:40.774+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 7, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:04:40.778+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:04:40.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.086 seconds
[2023-04-22T23:05:11.385+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:11.388+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:05:11.390+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:05:11.389+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:11.406+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:05:11.404+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 7, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:05:11.408+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:11.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.071 seconds
[2023-04-22T23:05:20.083+0000] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:20.086+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:05:20.088+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:05:20.088+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:20.115+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:05:20.109+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 7, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:05:20.116+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:20.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.074 seconds
[2023-04-22T23:05:39.334+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:39.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:05:39.337+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:05:39.337+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:39.344+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:05:39.343+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 28
    python_callable= my_arima.,
                              ^
SyntaxError: invalid syntax
[2023-04-22T23:05:39.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:05:39.372+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.046 seconds
[2023-04-22T23:06:09.734+0000] {processor.py:153} INFO - Started process (PID=342) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:09.737+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:06:09.739+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:06:09.739+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:09.747+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:06:09.746+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 28
    python_callable= my_arima.,
                              ^
SyntaxError: invalid syntax
[2023-04-22T23:06:09.748+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:09.779+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.053 seconds
[2023-04-22T23:06:40.379+0000] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:40.382+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:06:40.384+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:06:40.384+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:40.393+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:06:40.391+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 28
    python_callable= my_arima.,
                              ^
SyntaxError: invalid syntax
[2023-04-22T23:06:40.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:40.425+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.056 seconds
[2023-04-22T23:06:41.412+0000] {processor.py:153} INFO - Started process (PID=394) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:41.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:06:41.416+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:06:41.416+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:41.424+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:06:41.422+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 27
    python_callable= my_arima.,
                              ^
SyntaxError: invalid syntax
[2023-04-22T23:06:41.425+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:06:41.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.040 seconds
[2023-04-22T23:07:02.982+0000] {processor.py:153} INFO - Started process (PID=445) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:07:02.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:07:02.988+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:07:02.987+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:07:02.998+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:07:02.996+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 28
    python_callable= my_arima.,
                              ^
SyntaxError: invalid syntax
[2023-04-22T23:07:02.999+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:07:03.029+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.059 seconds
[2023-04-22T23:07:06.031+0000] {processor.py:153} INFO - Started process (PID=446) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:07:06.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:07:06.034+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:07:06.034+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:07:06.042+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:07:06.041+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 28
    python_callable= my_arima.,
                              ^
SyntaxError: invalid syntax
[2023-04-22T23:07:06.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:07:06.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.042 seconds
[2023-04-22T23:12:32.937+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:12:32.951+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:12:32.963+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:12:32.962+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:12:33.009+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:12:33.001+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:12:33.010+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:12:33.047+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.114 seconds
[2023-04-22T23:13:03.357+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:13:03.360+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:13:03.361+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:13:03.361+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:13:03.378+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:13:03.376+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:13:03.378+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:13:03.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.051 seconds
[2023-04-22T23:13:33.645+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:13:33.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:13:33.649+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:13:33.649+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:13:33.662+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:13:33.660+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:13:33.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:13:33.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.051 seconds
[2023-04-22T23:14:04.236+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:14:04.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:14:04.240+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:14:04.240+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:14:04.255+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:14:04.253+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:14:04.256+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:14:04.278+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.049 seconds
[2023-04-22T23:14:34.596+0000] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:14:34.598+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:14:34.600+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:14:34.599+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:14:34.614+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:14:34.612+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:14:34.615+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:14:34.639+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.051 seconds
[2023-04-22T23:15:05.040+0000] {processor.py:153} INFO - Started process (PID=290) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:15:05.043+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:15:05.044+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:15:05.044+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:15:05.061+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:15:05.059+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:15:05.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:15:05.082+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.049 seconds
[2023-04-22T23:15:35.475+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:15:35.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:15:35.482+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:15:35.482+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:15:35.500+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:15:35.498+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:15:35.502+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:15:35.529+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.071 seconds
[2023-04-22T23:16:05.626+0000] {processor.py:153} INFO - Started process (PID=392) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:16:05.633+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:16:05.638+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:16:05.637+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:16:05.663+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:16:05.660+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:16:05.664+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:16:05.717+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.105 seconds
[2023-04-22T23:16:36.092+0000] {processor.py:153} INFO - Started process (PID=443) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:16:36.095+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:16:36.096+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:16:36.096+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:16:36.111+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:16:36.109+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:16:36.112+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:16:36.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.051 seconds
[2023-04-22T23:17:06.315+0000] {processor.py:153} INFO - Started process (PID=494) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:17:06.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:17:06.319+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:17:06.318+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:17:06.334+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:17:06.332+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:17:06.336+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:17:06.356+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.047 seconds
[2023-04-22T23:17:36.527+0000] {processor.py:153} INFO - Started process (PID=545) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:17:36.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:17:36.530+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:17:36.530+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:17:36.545+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:17:36.542+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:17:36.545+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:17:36.572+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.055 seconds
[2023-04-22T23:18:00.750+0000] {processor.py:153} INFO - Started process (PID=596) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:00.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:18:00.758+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:18:00.757+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:00.798+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:18:00.795+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:18:00.798+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:00.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.096 seconds
[2023-04-22T23:18:29.410+0000] {processor.py:153} INFO - Started process (PID=647) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:29.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:18:29.416+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:18:29.416+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:29.436+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:18:29.434+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:18:29.437+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:29.467+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.076 seconds
[2023-04-22T23:18:31.440+0000] {processor.py:153} INFO - Started process (PID=648) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:31.442+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:18:31.444+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:18:31.443+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:31.466+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:18:31.464+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:18:31.467+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:18:31.491+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.057 seconds
[2023-04-22T23:19:28.533+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:19:28.536+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:19:28.538+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:19:28.538+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:19:28.559+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:19:28.556+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:19:28.560+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:19:28.604+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.080 seconds
[2023-04-22T23:19:58.833+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:19:58.836+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:19:58.838+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:19:58.838+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:19:58.851+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:19:58.849+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:19:58.853+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:19:58.878+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.054 seconds
[2023-04-22T23:20:28.965+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:20:28.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:20:28.967+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:20:28.967+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:20:28.978+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:20:28.976+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:20:28.979+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:20:28.998+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.038 seconds
[2023-04-22T23:20:59.194+0000] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:20:59.196+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:20:59.198+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:20:59.197+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:20:59.213+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:20:59.211+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:20:59.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:20:59.238+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.053 seconds
[2023-04-22T23:21:29.282+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:21:29.284+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:21:29.285+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:21:29.285+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:21:29.297+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:21:29.295+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:21:29.298+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:21:29.320+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.042 seconds
[2023-04-22T23:21:59.447+0000] {processor.py:153} INFO - Started process (PID=290) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:21:59.449+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:21:59.451+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:21:59.451+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:21:59.478+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:21:59.474+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:21:59.480+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:21:59.508+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.067 seconds
[2023-04-22T23:22:30.031+0000] {processor.py:153} INFO - Started process (PID=342) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:22:30.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:22:30.034+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:22:30.034+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:22:30.048+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:22:30.046+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:22:30.049+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:22:30.089+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.066 seconds
[2023-04-22T23:23:00.560+0000] {processor.py:153} INFO - Started process (PID=392) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:23:00.564+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:23:00.566+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:23:00.565+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:23:00.577+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:23:00.575+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:23:00.578+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:23:00.602+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.048 seconds
[2023-04-22T23:23:30.713+0000] {processor.py:153} INFO - Started process (PID=443) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:23:30.716+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:23:30.718+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:23:30.717+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:23:30.733+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:23:30.731+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:23:30.734+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:23:30.759+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.053 seconds
[2023-04-22T23:24:00.875+0000] {processor.py:153} INFO - Started process (PID=494) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:24:00.877+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:24:00.878+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:24:00.878+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:24:00.896+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:24:00.893+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:24:00.898+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:24:00.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.071 seconds
[2023-04-22T23:24:31.103+0000] {processor.py:153} INFO - Started process (PID=545) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:24:31.106+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:24:31.107+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:24:31.107+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:24:31.121+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:24:31.119+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:24:31.122+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:24:31.143+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.048 seconds
[2023-04-22T23:25:01.403+0000] {processor.py:153} INFO - Started process (PID=596) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:25:01.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:25:01.407+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:25:01.407+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:25:01.420+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:25:01.418+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:25:01.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:25:01.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.055 seconds
[2023-04-22T23:25:32.059+0000] {processor.py:153} INFO - Started process (PID=648) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:25:32.063+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:25:32.064+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:25:32.064+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:25:32.078+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:25:32.076+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:25:32.079+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:25:32.101+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.051 seconds
[2023-04-22T23:26:02.369+0000] {processor.py:153} INFO - Started process (PID=699) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:26:02.371+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:26:02.372+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:26:02.372+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:26:02.386+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:26:02.384+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:26:02.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:26:02.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.060 seconds
[2023-04-22T23:26:32.725+0000] {processor.py:153} INFO - Started process (PID=749) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:26:32.728+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:26:32.731+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:26:32.731+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:26:32.744+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:26:32.742+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:26:32.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:26:32.784+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.070 seconds
[2023-04-22T23:27:03.469+0000] {processor.py:153} INFO - Started process (PID=800) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:27:03.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:27:03.473+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:27:03.473+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:27:03.507+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:27:03.503+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:27:03.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:27:03.560+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.099 seconds
[2023-04-22T23:27:34.069+0000] {processor.py:153} INFO - Started process (PID=852) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:27:34.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:27:34.075+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:27:34.075+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:27:34.096+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:27:34.091+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:27:34.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:27:34.131+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.072 seconds
[2023-04-22T23:29:53.176+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:29:53.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:29:53.182+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:29:53.182+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:29:53.210+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:29:53.205+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:29:53.212+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:29:53.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.110 seconds
[2023-04-22T23:30:23.372+0000] {processor.py:153} INFO - Started process (PID=84) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:30:23.374+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:30:23.375+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:30:23.374+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:30:23.386+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:30:23.384+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:30:23.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:30:23.411+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.044 seconds
[2023-04-22T23:30:53.901+0000] {processor.py:153} INFO - Started process (PID=135) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:30:53.904+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:30:53.905+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:30:53.905+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:30:53.918+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:30:53.916+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:30:53.919+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:30:53.941+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.048 seconds
[2023-04-22T23:31:24.461+0000] {processor.py:153} INFO - Started process (PID=186) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:31:24.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:31:24.466+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:31:24.466+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:31:24.480+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:31:24.477+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:31:24.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:31:24.504+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.052 seconds
[2023-04-22T23:31:54.668+0000] {processor.py:153} INFO - Started process (PID=237) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:31:54.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:31:54.673+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:31:54.673+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:31:54.696+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:31:54.693+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:31:54.697+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:31:54.727+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.071 seconds
[2023-04-22T23:32:25.134+0000] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:32:25.140+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:32:25.143+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:32:25.143+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:32:25.167+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:32:25.164+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:32:25.168+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:32:25.199+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.085 seconds
[2023-04-22T23:32:55.364+0000] {processor.py:153} INFO - Started process (PID=339) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:32:55.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:32:55.369+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:32:55.368+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:32:55.387+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:32:55.385+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:32:55.389+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:32:55.425+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.070 seconds
[2023-04-22T23:33:25.585+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:33:25.588+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:33:25.590+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:33:25.590+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:33:25.606+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:33:25.602+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:33:25.608+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:33:25.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.065 seconds
[2023-04-22T23:33:55.793+0000] {processor.py:153} INFO - Started process (PID=440) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:33:55.797+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:33:55.799+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:33:55.799+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:33:55.818+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:33:55.815+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 8, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:33:55.818+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:33:55.851+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.074 seconds
[2023-04-22T23:38:43.058+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:38:43.061+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:38:43.062+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:38:43.062+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:38:43.086+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:38:43.078+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:38:43.088+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:38:43.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.075 seconds
[2023-04-22T23:39:13.283+0000] {processor.py:153} INFO - Started process (PID=84) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:39:13.285+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:39:13.287+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:39:13.287+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:39:13.306+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:39:13.304+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:39:13.307+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:39:13.352+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.078 seconds
[2023-04-22T23:39:43.403+0000] {processor.py:153} INFO - Started process (PID=135) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:39:43.405+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:39:43.406+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:39:43.406+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:39:43.417+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:39:43.416+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:39:43.418+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:39:43.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.039 seconds
[2023-04-22T23:40:13.945+0000] {processor.py:153} INFO - Started process (PID=186) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:40:13.946+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:40:13.948+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:40:13.948+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:40:13.970+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:40:13.968+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:40:13.971+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:40:14.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.061 seconds
[2023-04-22T23:40:44.360+0000] {processor.py:153} INFO - Started process (PID=237) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:40:44.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:40:44.364+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:40:44.364+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:40:44.380+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:40:44.378+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:40:44.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:40:44.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.056 seconds
[2023-04-22T23:41:15.117+0000] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:41:15.119+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:41:15.121+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:41:15.121+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:41:15.139+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:41:15.136+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:41:15.139+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:41:15.168+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.057 seconds
[2023-04-22T23:41:45.333+0000] {processor.py:153} INFO - Started process (PID=339) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:41:45.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:41:45.337+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:41:45.337+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:41:45.353+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:41:45.351+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:41:45.355+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:41:45.379+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.052 seconds
[2023-04-22T23:42:15.842+0000] {processor.py:153} INFO - Started process (PID=390) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:42:15.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:42:15.845+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:42:15.845+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:42:15.857+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:42:15.856+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:42:15.858+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:42:15.878+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.044 seconds
[2023-04-22T23:43:05.505+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:43:05.507+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:43:05.508+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:43:05.508+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:43:05.538+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:43:05.534+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:43:05.539+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:43:05.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.068 seconds
[2023-04-22T23:43:23.205+0000] {processor.py:153} INFO - Started process (PID=77) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:43:23.207+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:43:23.209+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:43:23.209+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:43:23.225+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:43:23.223+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:43:23.226+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:43:23.251+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.053 seconds
[2023-04-22T23:44:29.232+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:44:29.233+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:44:29.235+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:44:29.234+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:44:29.251+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:44:29.246+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:44:29.253+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:44:29.279+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.050 seconds
[2023-04-22T23:46:53.116+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:46:53.119+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:46:53.121+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:46:53.120+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:46:53.137+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:46:53.135+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:46:53.138+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:46:53.172+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.062 seconds
[2023-04-22T23:47:23.492+0000] {processor.py:153} INFO - Started process (PID=85) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:47:23.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:47:23.507+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:47:23.507+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:47:23.534+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:47:23.530+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:47:23.536+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:47:23.593+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.113 seconds
[2023-04-22T23:47:54.240+0000] {processor.py:153} INFO - Started process (PID=136) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:47:54.243+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:47:54.244+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:47:54.244+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:47:54.259+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:47:54.257+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:47:54.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:47:54.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.053 seconds
[2023-04-22T23:48:24.671+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:48:24.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:48:24.675+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:48:24.675+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:48:24.690+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:48:24.688+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:48:24.691+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:48:24.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.056 seconds
[2023-04-22T23:48:55.096+0000] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:48:55.097+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:48:55.099+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:48:55.099+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:48:55.111+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:48:55.109+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:48:55.113+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:48:55.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.045 seconds
[2023-04-22T23:49:25.541+0000] {processor.py:153} INFO - Started process (PID=289) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:49:25.545+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:49:25.547+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:49:25.547+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:49:25.570+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:49:25.567+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:49:25.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:49:25.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.103 seconds
[2023-04-22T23:49:56.442+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:49:56.444+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:49:56.446+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:49:56.446+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:49:56.466+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:49:56.463+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:49:56.467+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:49:56.495+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.061 seconds
[2023-04-22T23:50:27.142+0000] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/models_dags.py
[2023-04-22T23:50:27.145+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-22T23:50:27.146+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:50:27.146+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-22T23:50:27.157+0000] {logging_mixin.py:137} INFO - [2023-04-22T23:50:27.155+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-22T23:50:27.158+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-22T23:50:27.184+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.046 seconds
