[2023-04-23T00:00:55.741+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:00:55.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:00:55.744+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:00:55.744+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:00:55.760+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:00:55.758+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:00:55.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:00:55.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.050 seconds
[2023-04-23T00:01:26.162+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:01:26.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:01:26.167+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:26.166+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:01:26.181+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:26.178+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:01:26.182+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:01:26.207+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.053 seconds
[2023-04-23T00:01:56.853+0000] {processor.py:153} INFO - Started process (PID=138) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:01:56.856+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:01:56.864+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:56.864+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:01:56.877+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:56.876+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:01:56.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:01:56.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.058 seconds
[2023-04-23T00:02:26.963+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:02:26.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:02:26.965+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:26.965+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:02:26.974+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:26.972+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:02:26.974+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:02:26.993+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.034 seconds
[2023-04-23T00:02:57.467+0000] {processor.py:153} INFO - Started process (PID=241) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:02:57.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:02:57.474+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:57.474+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:02:57.500+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:57.496+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:02:57.501+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:02:57.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.093 seconds
[2023-04-23T00:04:50.066+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:04:50.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:04:50.076+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:04:50.076+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:04:50.107+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:04:50.104+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:04:50.108+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:04:50.155+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.095 seconds
[2023-04-23T00:05:20.463+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:05:20.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:05:20.468+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:20.468+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:05:20.508+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:20.502+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:05:20.509+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:05:20.565+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.110 seconds
[2023-04-23T00:05:51.242+0000] {processor.py:153} INFO - Started process (PID=138) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:05:51.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:05:51.247+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:51.247+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:05:51.528+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:51.526+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:05:51.529+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:05:51.558+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.324 seconds
[2023-04-23T00:06:21.636+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:06:21.639+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:06:21.640+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:21.640+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:06:21.653+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:21.651+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:06:21.654+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:06:21.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.045 seconds
[2023-04-23T00:06:52.403+0000] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:06:52.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:06:52.414+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:52.412+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:06:52.483+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:52.476+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:06:52.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:06:52.608+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.215 seconds
[2023-04-23T00:07:49.435+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:07:49.440+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:07:49.442+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:07:49.442+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:07:49.478+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:07:49.475+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:07:49.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:07:49.529+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.102 seconds
[2023-04-23T00:08:20.202+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:08:20.207+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:08:20.208+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:08:20.208+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:08:20.228+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:08:20.226+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:08:20.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:08:20.256+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.073 seconds
[2023-04-23T00:09:23.985+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:09:23.988+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:09:23.990+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:23.990+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:09:24.010+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:24.008+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:09:24.012+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:09:24.064+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.090 seconds
[2023-04-23T00:09:54.768+0000] {processor.py:153} INFO - Started process (PID=88) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:09:54.770+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:09:54.772+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:54.772+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:09:54.793+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:54.786+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:09:54.797+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:09:54.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.072 seconds
[2023-04-23T00:10:24.990+0000] {processor.py:153} INFO - Started process (PID=139) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:10:24.992+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:10:24.993+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:24.993+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:10:25.287+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:25.285+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:10:25.287+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:10:25.307+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.323 seconds
[2023-04-23T00:10:55.813+0000] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:10:55.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:10:55.816+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:55.816+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:10:55.833+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:55.831+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:10:55.834+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:10:55.877+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.074 seconds
[2023-04-23T00:11:25.920+0000] {processor.py:153} INFO - Started process (PID=241) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:11:25.921+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:11:25.922+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:25.922+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:11:25.929+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:25.928+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:11:25.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:11:25.952+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.037 seconds
[2023-04-23T00:11:56.626+0000] {processor.py:153} INFO - Started process (PID=292) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:11:56.628+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:11:56.630+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:56.630+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:11:56.645+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:56.642+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:11:56.647+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:11:56.697+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.075 seconds
[2023-04-23T00:12:27.347+0000] {processor.py:153} INFO - Started process (PID=343) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:12:27.349+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:12:27.350+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:27.350+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:12:27.359+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:27.357+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:12:27.360+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:12:27.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.039 seconds
[2023-04-23T00:12:58.219+0000] {processor.py:153} INFO - Started process (PID=394) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:12:58.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:12:58.221+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:58.221+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:12:58.229+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:58.228+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:12:58.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:12:58.251+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.036 seconds
[2023-04-23T00:13:28.885+0000] {processor.py:153} INFO - Started process (PID=445) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:13:28.887+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:13:28.888+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:28.888+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:13:28.898+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:28.897+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:13:28.899+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:13:28.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.036 seconds
[2023-04-23T00:13:59.454+0000] {processor.py:153} INFO - Started process (PID=496) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:13:59.456+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:13:59.457+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:59.457+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:13:59.467+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:59.466+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:13:59.469+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:13:59.496+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.049 seconds
[2023-04-23T00:14:30.148+0000] {processor.py:153} INFO - Started process (PID=547) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:14:30.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:14:30.151+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:14:30.151+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:14:30.159+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:14:30.158+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:14:30.160+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:14:30.177+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.034 seconds
[2023-04-23T00:15:50.118+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:15:50.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:15:50.128+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:15:50.128+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:15:50.171+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:15:50.158+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:15:50.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:15:50.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.095 seconds
[2023-04-23T00:16:20.327+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:16:20.332+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:16:20.335+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:20.335+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:16:20.359+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:20.356+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:16:20.360+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:16:20.395+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.078 seconds
[2023-04-23T00:16:50.677+0000] {processor.py:153} INFO - Started process (PID=138) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:16:50.680+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:16:50.686+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:50.686+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:16:50.991+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:50.989+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:16:50.992+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:16:51.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.347 seconds
[2023-04-23T00:17:21.370+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:17:21.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:17:21.373+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:21.373+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:17:21.397+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:21.395+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:17:21.398+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:17:21.418+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.052 seconds
[2023-04-23T00:17:51.971+0000] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:17:51.973+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:17:51.974+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:51.974+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:17:51.992+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:51.987+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:17:51.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:17:52.058+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.107 seconds
[2023-04-23T00:19:13.898+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:19:13.900+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:19:13.902+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:13.901+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:19:13.921+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:13.919+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:19:13.922+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:19:13.955+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.070 seconds
[2023-04-23T00:19:44.039+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:19:44.040+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:19:44.041+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:44.041+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:19:44.048+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:44.047+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:19:44.049+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:19:44.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.033 seconds
[2023-04-23T00:21:04.404+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:21:04.408+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:21:04.410+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:21:04.409+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:21:04.437+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:21:04.431+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:21:04.438+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:21:04.471+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.072 seconds
[2023-04-23T00:22:15.881+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:22:15.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:22:15.885+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:15.885+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:22:15.910+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:15.902+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:22:15.914+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:22:15.949+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.072 seconds
[2023-04-23T00:22:46.661+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:22:46.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:22:46.666+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:46.665+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:22:46.684+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:46.682+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:22:46.684+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:22:46.707+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.055 seconds
[2023-04-23T00:24:20.829+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:24:20.833+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:24:20.835+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:24:20.835+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:24:20.876+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:24:20.872+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:24:20.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:24:20.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.096 seconds
[2023-04-23T00:25:57.465+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:25:57.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:25:57.469+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:25:57.469+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:25:57.502+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:25:57.500+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:25:57.507+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:25:57.558+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.098 seconds
[2023-04-23T00:26:27.860+0000] {processor.py:153} INFO - Started process (PID=88) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:26:27.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:26:27.864+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:27.864+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:26:27.884+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:27.882+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:26:27.885+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:26:27.938+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.085 seconds
[2023-04-23T00:26:58.478+0000] {processor.py:153} INFO - Started process (PID=139) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:26:58.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:26:58.482+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:58.482+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:26:58.499+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:58.497+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:26:58.500+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:26:58.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.073 seconds
[2023-04-23T00:27:29.169+0000] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:27:29.172+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:27:29.174+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:27:29.174+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:27:29.201+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:27:29.198+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:27:29.202+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:27:29.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.098 seconds
[2023-04-23T00:28:00.315+0000] {processor.py:153} INFO - Started process (PID=241) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:28:00.320+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:28:00.324+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:00.323+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:28:00.354+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:00.349+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:28:00.356+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:28:00.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.154 seconds
[2023-04-23T00:28:31.601+0000] {processor.py:153} INFO - Started process (PID=292) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:28:31.614+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:28:31.625+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:31.624+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:28:31.660+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:31.655+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:28:31.661+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:28:31.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.123 seconds
[2023-04-23T00:52:27.913+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:52:27.915+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:52:27.916+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:52:27.916+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:52:29.068+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:52:29.064+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:52:29.069+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:52:29.091+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.182 seconds
[2023-04-23T00:52:59.174+0000] {processor.py:153} INFO - Started process (PID=92) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:52:59.179+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:52:59.181+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:52:59.180+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:52:59.598+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:52:59.595+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:52:59.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:52:59.623+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.454 seconds
[2023-04-23T00:53:10.787+0000] {processor.py:153} INFO - Started process (PID=132) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:53:10.790+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:53:10.792+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:53:10.792+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:53:11.212+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:53:11.209+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:53:11.212+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:53:11.233+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.455 seconds
[2023-04-23T00:53:41.533+0000] {processor.py:153} INFO - Started process (PID=184) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:53:41.536+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:53:41.539+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:53:41.539+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:53:41.792+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:53:41.789+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:53:41.795+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:53:41.812+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.288 seconds
[2023-04-23T00:54:12.395+0000] {processor.py:153} INFO - Started process (PID=236) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:54:12.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:54:12.405+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:54:12.405+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:54:12.866+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:54:12.861+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:54:12.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:54:12.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.515 seconds
[2023-04-23T00:56:28.080+0000] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:56:28.088+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:56:28.096+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:56:28.095+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:56:29.752+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:56:29.750+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:56:29.753+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:56:29.767+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.704 seconds
[2023-04-23T00:57:50.370+0000] {processor.py:153} INFO - Started process (PID=290) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:57:50.373+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:57:50.375+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:57:50.375+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:57:50.832+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:57:50.830+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:57:50.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:57:50.844+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.494 seconds
[2023-04-23T00:58:33.838+0000] {processor.py:153} INFO - Started process (PID=342) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:58:33.849+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:58:33.865+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:58:33.864+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:58:35.158+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:58:35.156+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:58:35.159+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:58:35.176+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.365 seconds
[2023-04-23T00:59:51.426+0000] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T00:59:51.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T00:59:51.431+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:59:51.431+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T00:59:51.896+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:59:51.893+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T00:59:51.897+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T00:59:51.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.502 seconds
[2023-04-23T01:01:36.404+0000] {processor.py:153} INFO - Started process (PID=446) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:01:36.408+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:01:36.410+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:01:36.409+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:01:36.850+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:01:36.848+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:01:36.851+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:01:36.864+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.477 seconds
[2023-04-23T01:03:39.460+0000] {processor.py:153} INFO - Started process (PID=499) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:03:39.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:03:39.465+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:03:39.465+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:03:39.891+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:03:39.889+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:03:39.891+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:03:39.904+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.468 seconds
[2023-04-23T01:09:03.117+0000] {processor.py:153} INFO - Started process (PID=551) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:09:03.120+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:09:03.122+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:09:03.121+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:09:04.904+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:09:04.902+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:09:04.905+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:09:04.919+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.810 seconds
[2023-04-23T01:09:35.891+0000] {processor.py:153} INFO - Started process (PID=607) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:09:35.894+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:09:35.895+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:09:35.895+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:09:36.344+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:09:36.342+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:09:36.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:09:36.358+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.473 seconds
[2023-04-23T01:10:06.412+0000] {processor.py:153} INFO - Started process (PID=661) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:10:06.413+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:10:06.414+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:10:06.414+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:10:06.824+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:10:06.822+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:10:06.824+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:10:06.839+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.430 seconds
[2023-04-23T01:10:36.965+0000] {processor.py:153} INFO - Started process (PID=715) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:10:36.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:10:36.967+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:10:36.967+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:10:37.662+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:10:37.660+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:10:37.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:10:37.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.716 seconds
[2023-04-23T01:11:08.423+0000] {processor.py:153} INFO - Started process (PID=769) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:11:08.426+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:11:08.427+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:11:08.427+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:11:09.033+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:11:09.031+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:11:09.034+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:11:09.048+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.632 seconds
[2023-04-23T01:11:39.849+0000] {processor.py:153} INFO - Started process (PID=823) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:11:39.852+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:11:39.853+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:11:39.853+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:11:40.281+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:11:40.279+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:11:40.282+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:11:40.295+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.454 seconds
[2023-04-23T01:12:10.354+0000] {processor.py:153} INFO - Started process (PID=882) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:12:10.356+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:12:10.357+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:12:10.357+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:12:10.769+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:12:10.767+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:12:10.770+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:12:10.785+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.436 seconds
[2023-04-23T01:12:41.166+0000] {processor.py:153} INFO - Started process (PID=934) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:12:41.169+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:12:41.170+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:12:41.170+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:12:41.593+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:12:41.591+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:12:41.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:12:41.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.451 seconds
[2023-04-23T01:13:12.165+0000] {processor.py:153} INFO - Started process (PID=986) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:13:12.168+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:13:12.169+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:13:12.169+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:13:12.574+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:13:12.571+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:13:12.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:13:12.595+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.437 seconds
[2023-04-23T01:13:42.659+0000] {processor.py:153} INFO - Started process (PID=1041) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:13:42.661+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:13:42.662+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:13:42.661+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:13:43.045+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:13:43.043+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:13:43.046+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:13:43.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.403 seconds
[2023-04-23T01:14:13.301+0000] {processor.py:153} INFO - Started process (PID=1096) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:14:13.303+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:14:13.304+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:14:13.304+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:14:13.880+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:14:13.878+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:14:13.881+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:14:13.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.599 seconds
[2023-04-23T01:14:44.140+0000] {processor.py:153} INFO - Started process (PID=1144) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:14:44.142+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:14:44.142+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:14:44.142+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:14:44.573+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:14:44.571+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:14:44.574+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:14:44.595+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.460 seconds
[2023-04-23T01:15:14.673+0000] {processor.py:153} INFO - Started process (PID=1199) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:15:14.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:15:14.675+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:15:14.675+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:15:15.050+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:15:15.048+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:15:15.050+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:15:15.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.393 seconds
[2023-04-23T01:15:45.118+0000] {processor.py:153} INFO - Started process (PID=1254) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:15:45.119+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:15:45.119+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:15:45.119+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:15:45.477+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:15:45.475+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:15:45.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:15:45.494+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.380 seconds
[2023-04-23T01:16:16.481+0000] {processor.py:153} INFO - Started process (PID=1306) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:16:16.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:16:16.484+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:16:16.484+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:16:16.881+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:16:16.879+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:16:16.882+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:16:16.897+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.423 seconds
[2023-04-23T01:16:47.264+0000] {processor.py:153} INFO - Started process (PID=1358) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:16:47.267+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:16:47.269+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:16:47.269+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:16:47.666+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:16:47.664+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:16:47.666+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:16:47.680+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.427 seconds
[2023-04-23T01:17:17.802+0000] {processor.py:153} INFO - Started process (PID=1414) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:17:17.803+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:17:17.804+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:17:17.804+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:17:18.198+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:17:18.194+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:17:18.199+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:17:18.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.429 seconds
[2023-04-23T01:17:48.993+0000] {processor.py:153} INFO - Started process (PID=1466) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:17:48.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:17:48.998+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:17:48.998+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:17:49.411+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:17:49.409+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:17:49.412+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:17:49.428+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.442 seconds
[2023-04-23T01:18:20.280+0000] {processor.py:153} INFO - Started process (PID=1520) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:18:20.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:18:20.285+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:18:20.284+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:18:20.683+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:18:20.682+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:18:20.684+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:18:20.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.426 seconds
[2023-04-23T01:18:51.116+0000] {processor.py:153} INFO - Started process (PID=1572) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:18:51.118+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:18:51.120+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:18:51.120+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:18:51.595+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:18:51.592+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:18:51.596+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:18:51.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.502 seconds
[2023-04-23T01:19:21.814+0000] {processor.py:153} INFO - Started process (PID=1624) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:19:21.817+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:19:21.819+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:19:21.819+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:19:22.607+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:19:22.602+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:19:22.609+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:19:22.647+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.855 seconds
[2023-04-23T01:19:53.317+0000] {processor.py:153} INFO - Started process (PID=1678) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:19:53.320+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:19:53.321+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:19:53.321+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:19:53.707+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:19:53.705+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:19:53.707+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:19:53.719+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.411 seconds
[2023-04-23T01:20:24.064+0000] {processor.py:153} INFO - Started process (PID=1730) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:20:24.066+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:20:24.068+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:20:24.068+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:20:24.460+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:20:24.458+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:20:24.461+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:20:24.480+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.424 seconds
[2023-04-23T01:20:54.683+0000] {processor.py:153} INFO - Started process (PID=1782) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:20:54.687+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:20:54.689+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:20:54.688+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:20:55.132+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:20:55.130+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:20:55.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:20:55.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.478 seconds
[2023-04-23T01:21:25.375+0000] {processor.py:153} INFO - Started process (PID=1834) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:21:25.377+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:21:25.379+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:21:25.378+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:21:25.835+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:21:25.832+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:21:25.836+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:21:25.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.483 seconds
[2023-04-23T01:21:56.037+0000] {processor.py:153} INFO - Started process (PID=1886) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:21:56.040+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:21:56.044+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:21:56.044+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:21:56.481+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:21:56.479+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:21:56.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:21:56.495+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.467 seconds
[2023-04-23T01:22:26.796+0000] {processor.py:153} INFO - Started process (PID=1938) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:22:26.800+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:22:26.807+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:22:26.807+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:22:27.288+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:22:27.286+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:22:27.288+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:22:27.303+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.517 seconds
[2023-04-23T01:22:58.261+0000] {processor.py:153} INFO - Started process (PID=1993) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:22:58.263+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:22:58.264+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:22:58.264+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:22:58.701+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:22:58.699+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:22:58.701+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:22:58.715+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.460 seconds
[2023-04-23T01:23:29.163+0000] {processor.py:153} INFO - Started process (PID=2045) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:23:29.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:23:29.166+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:23:29.166+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:23:29.586+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:23:29.585+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:23:29.587+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:23:29.600+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.443 seconds
[2023-04-23T01:23:59.673+0000] {processor.py:153} INFO - Started process (PID=2101) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:23:59.675+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:23:59.676+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:23:59.676+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:24:00.118+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:24:00.116+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:24:00.119+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:24:00.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.463 seconds
[2023-04-23T01:24:30.992+0000] {processor.py:153} INFO - Started process (PID=2155) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:24:30.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:24:30.996+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:24:30.996+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:24:31.380+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:24:31.379+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:24:31.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:24:31.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.407 seconds
[2023-04-23T01:25:01.643+0000] {processor.py:153} INFO - Started process (PID=2207) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:25:01.646+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:25:01.648+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:25:01.647+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:25:02.056+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:25:02.054+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:25:02.057+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:25:02.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.434 seconds
[2023-04-23T01:25:32.197+0000] {processor.py:153} INFO - Started process (PID=2259) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:25:32.200+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:25:32.202+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:25:32.201+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:25:32.592+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:25:32.590+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:25:32.593+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:25:32.605+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.415 seconds
[2023-04-23T01:26:02.950+0000] {processor.py:153} INFO - Started process (PID=2311) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:26:02.951+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:26:02.953+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:26:02.953+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:26:03.347+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:26:03.345+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:26:03.347+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:26:03.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.416 seconds
[2023-04-23T01:26:33.674+0000] {processor.py:153} INFO - Started process (PID=2363) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:26:33.676+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:26:33.678+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:26:33.678+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:26:34.106+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:26:34.104+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:26:34.106+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:26:34.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.450 seconds
[2023-04-23T01:27:04.495+0000] {processor.py:153} INFO - Started process (PID=2415) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:27:04.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:27:04.499+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:27:04.499+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:27:04.921+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:27:04.919+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:27:04.922+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:27:04.934+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.445 seconds
[2023-04-23T01:27:35.286+0000] {processor.py:153} INFO - Started process (PID=2467) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:27:35.289+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:27:35.291+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:27:35.291+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:27:35.688+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:27:35.686+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:27:35.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:27:35.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.423 seconds
[2023-04-23T01:28:05.952+0000] {processor.py:153} INFO - Started process (PID=2519) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:28:05.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:28:05.956+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:28:05.956+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:28:06.336+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:28:06.334+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:28:06.336+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:28:06.349+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.401 seconds
[2023-04-23T01:28:36.466+0000] {processor.py:153} INFO - Started process (PID=2571) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:28:36.469+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:28:36.470+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:28:36.470+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:28:36.893+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:28:36.891+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:28:36.894+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:28:36.905+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.447 seconds
[2023-04-23T01:29:07.395+0000] {processor.py:153} INFO - Started process (PID=2623) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:29:07.397+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:29:07.398+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:29:07.398+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:29:07.834+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:29:07.832+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:29:07.834+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:29:07.847+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.457 seconds
[2023-04-23T01:29:38.381+0000] {processor.py:153} INFO - Started process (PID=2675) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:29:38.384+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:29:38.385+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:29:38.385+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:29:38.785+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:29:38.783+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:29:38.786+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:29:38.797+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.423 seconds
[2023-04-23T01:30:09.235+0000] {processor.py:153} INFO - Started process (PID=2727) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:30:09.238+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:30:09.239+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:30:09.239+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:30:09.596+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:30:09.594+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:30:09.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:30:09.616+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.388 seconds
[2023-04-23T01:30:39.977+0000] {processor.py:153} INFO - Started process (PID=2779) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:30:39.980+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:30:39.981+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:30:39.981+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:30:40.364+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:30:40.361+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:30:40.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:30:40.377+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.408 seconds
[2023-04-23T01:31:10.835+0000] {processor.py:153} INFO - Started process (PID=2830) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:31:10.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:31:10.841+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:31:10.840+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:31:11.309+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:31:11.307+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:31:11.310+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:31:11.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.498 seconds
[2023-04-23T01:31:42.211+0000] {processor.py:153} INFO - Started process (PID=2885) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:31:42.213+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:31:42.214+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:31:42.214+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:31:42.582+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:31:42.579+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:31:42.583+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:31:42.601+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.395 seconds
[2023-04-23T01:32:13.607+0000] {processor.py:153} INFO - Started process (PID=2939) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:32:13.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:32:13.611+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:32:13.611+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:32:14.031+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:32:14.027+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:32:14.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:32:14.053+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.451 seconds
[2023-04-23T01:32:44.776+0000] {processor.py:153} INFO - Started process (PID=2991) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:32:44.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:32:44.780+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:32:44.780+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:32:45.182+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:32:45.179+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:32:45.183+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:32:45.203+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.432 seconds
[2023-04-23T01:33:15.280+0000] {processor.py:153} INFO - Started process (PID=3043) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:33:15.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:33:15.284+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:33:15.284+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:33:15.678+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:33:15.674+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:33:15.679+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:33:15.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.427 seconds
[2023-04-23T01:33:46.483+0000] {processor.py:153} INFO - Started process (PID=3101) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:33:46.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:33:46.487+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:33:46.487+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:33:46.877+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:33:46.875+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:33:46.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:33:46.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.420 seconds
[2023-04-23T01:34:17.844+0000] {processor.py:153} INFO - Started process (PID=3153) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:34:17.846+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:34:17.847+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:34:17.847+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:34:18.171+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:34:18.169+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:34:18.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:34:18.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.352 seconds
[2023-04-23T01:34:48.937+0000] {processor.py:153} INFO - Started process (PID=3206) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:34:48.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:34:48.942+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:34:48.942+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:34:49.301+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:34:49.298+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:34:49.302+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:34:49.318+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.388 seconds
[2023-04-23T01:35:20.285+0000] {processor.py:153} INFO - Started process (PID=3258) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:35:20.288+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:35:20.289+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:35:20.289+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:35:20.641+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:35:20.639+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:35:20.641+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:35:20.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.380 seconds
[2023-04-23T01:35:51.416+0000] {processor.py:153} INFO - Started process (PID=3310) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:35:51.423+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:35:51.427+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:35:51.425+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:35:51.946+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:35:51.943+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:35:51.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:35:51.971+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.562 seconds
[2023-04-23T01:36:22.888+0000] {processor.py:153} INFO - Started process (PID=3362) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:36:22.890+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:36:22.891+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:36:22.891+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:36:23.881+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:36:23.869+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:36:23.883+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:36:23.931+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.051 seconds
[2023-04-23T01:36:33.218+0000] {processor.py:153} INFO - Started process (PID=3366) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:36:33.221+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:36:33.224+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:36:33.223+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:36:33.637+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:36:33.634+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:36:33.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:36:33.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.445 seconds
[2023-04-23T01:52:16.075+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:52:16.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:52:16.085+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:52:16.084+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:52:17.614+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:52:17.610+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:52:17.615+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:52:17.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.582 seconds
[2023-04-23T01:52:47.950+0000] {processor.py:153} INFO - Started process (PID=90) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:52:47.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:52:47.954+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:52:47.954+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:52:48.419+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:52:48.417+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:52:48.419+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:52:48.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.489 seconds
[2023-04-23T01:53:19.357+0000] {processor.py:153} INFO - Started process (PID=144) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:53:19.360+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:53:19.361+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:53:19.361+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:53:19.815+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:53:19.813+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:53:19.816+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:53:19.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.476 seconds
[2023-04-23T01:53:50.138+0000] {processor.py:153} INFO - Started process (PID=196) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:53:50.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:53:50.142+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:53:50.142+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:53:50.638+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:53:50.636+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:53:50.639+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:53:50.654+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.523 seconds
[2023-04-23T01:54:20.759+0000] {processor.py:153} INFO - Started process (PID=250) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:54:20.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:54:20.761+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:54:20.761+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:54:21.182+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:54:21.180+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:54:21.182+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:54:21.194+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.438 seconds
[2023-04-23T01:54:51.452+0000] {processor.py:153} INFO - Started process (PID=304) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:54:51.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:54:51.455+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:54:51.454+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:54:51.955+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:54:51.953+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:54:51.956+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:54:51.997+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.547 seconds
[2023-04-23T01:55:22.986+0000] {processor.py:153} INFO - Started process (PID=359) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:55:22.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:55:22.990+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:55:22.990+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:55:23.363+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:55:23.361+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:55:23.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:55:23.376+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.398 seconds
[2023-04-23T01:55:54.068+0000] {processor.py:153} INFO - Started process (PID=412) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:55:54.071+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:55:54.073+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:55:54.073+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:55:54.574+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:55:54.572+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:55:54.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:55:54.591+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.533 seconds
[2023-04-23T01:56:24.690+0000] {processor.py:153} INFO - Started process (PID=464) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:56:24.693+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:56:24.695+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:56:24.694+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:56:25.053+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:56:25.051+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:56:25.053+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:56:25.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.384 seconds
[2023-04-23T01:56:55.315+0000] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:56:55.318+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:56:55.323+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:56:55.321+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:56:55.853+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:56:55.842+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:56:55.856+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:56:55.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.599 seconds
[2023-04-23T01:57:26.066+0000] {processor.py:153} INFO - Started process (PID=569) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:57:26.068+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:57:26.069+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:57:26.068+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:57:26.648+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:57:26.646+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:57:26.649+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:57:26.664+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.602 seconds
[2023-04-23T01:57:56.857+0000] {processor.py:153} INFO - Started process (PID=625) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:57:56.858+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:57:56.860+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:57:56.859+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:57:57.350+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:57:57.340+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:57:57.351+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:57:57.371+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.518 seconds
[2023-04-23T01:58:28.368+0000] {processor.py:153} INFO - Started process (PID=678) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:58:28.370+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:58:28.371+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:58:28.371+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:58:28.813+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:58:28.811+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:58:28.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:58:28.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.470 seconds
[2023-04-23T01:58:59.181+0000] {processor.py:153} INFO - Started process (PID=730) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:58:59.185+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:58:59.188+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:58:59.188+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:58:59.743+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:58:59.741+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:58:59.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:58:59.765+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.598 seconds
[2023-04-23T01:59:29.968+0000] {processor.py:153} INFO - Started process (PID=786) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T01:59:29.969+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T01:59:29.970+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:59:29.970+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T01:59:30.386+0000] {logging_mixin.py:137} INFO - [2023-04-23T01:59:30.384+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags.py", line 10, in <module>
    from statsmodels.tsa.arima.model import ARIMA
ModuleNotFoundError: No module named 'statsmodels'
[2023-04-23T01:59:30.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T01:59:30.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.436 seconds
[2023-04-23T02:56:26.677+0000] {processor.py:153} INFO - Started process (PID=51) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T02:56:26.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T02:56:26.683+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:26.682+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T02:56:28.180+0000] {processor.py:753} INFO - DAG(s) dict_keys(['modelservice']) retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T02:56:28.326+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:28.325+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:modelservice
[2023-04-23T02:56:28.331+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:28.331+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:modelservice
[2023-04-23T02:56:28.335+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:28.335+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:modelservice
[2023-04-23T02:56:28.336+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:28.335+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-23T02:56:28.345+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:28.344+0000] {dag.py:2726} INFO - Creating ORM DAG for modelservice
[2023-04-23T02:56:28.353+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:28.353+0000] {dag.py:3456} INFO - Setting next_dagrun for modelservice to 2023-05-01T01:30:00+00:00, run_after=2023-05-15T01:30:00+00:00
[2023-04-23T02:56:28.365+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.695 seconds
[2023-04-23T02:56:58.814+0000] {processor.py:153} INFO - Started process (PID=60) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T02:56:58.816+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T02:56:58.818+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:58.818+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T02:56:59.640+0000] {processor.py:753} INFO - DAG(s) dict_keys(['modelservice']) retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T02:56:59.670+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:59.669+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-23T02:56:59.688+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:56:59.688+0000] {dag.py:3456} INFO - Setting next_dagrun for modelservice to 2023-05-01T01:30:00+00:00, run_after=2023-05-15T01:30:00+00:00
[2023-04-23T02:56:59.722+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.917 seconds
[2023-04-23T02:57:30.183+0000] {processor.py:153} INFO - Started process (PID=68) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T02:57:30.186+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T02:57:30.188+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:57:30.187+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T02:57:31.041+0000] {processor.py:753} INFO - DAG(s) dict_keys(['modelservice']) retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T02:57:31.080+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:57:31.079+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-23T02:57:31.101+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:57:31.100+0000] {dag.py:3456} INFO - Setting next_dagrun for modelservice to 2023-05-01T01:30:00+00:00, run_after=2023-05-15T01:30:00+00:00
[2023-04-23T02:57:31.120+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.949 seconds
[2023-04-23T02:58:01.692+0000] {processor.py:153} INFO - Started process (PID=77) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T02:58:01.695+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T02:58:01.697+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:58:01.697+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T02:58:02.442+0000] {processor.py:753} INFO - DAG(s) dict_keys(['modelservice']) retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T02:58:02.472+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:58:02.471+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-23T02:58:02.492+0000] {logging_mixin.py:137} INFO - [2023-04-23T02:58:02.492+0000] {dag.py:3456} INFO - Setting next_dagrun for modelservice to 2023-05-01T01:30:00+00:00, run_after=2023-05-15T01:30:00+00:00
[2023-04-23T02:58:02.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.823 seconds
[2023-04-23T05:53:21.188+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T05:53:21.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T05:53:21.191+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:21.191+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T05:53:23.614+0000] {processor.py:753} INFO - DAG(s) dict_keys(['modelservice']) retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T05:53:24.144+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:24.144+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:modelservice
[2023-04-23T05:53:24.170+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:24.170+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:modelservice
[2023-04-23T05:53:24.184+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:24.184+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:modelservice
[2023-04-23T05:53:24.186+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:24.185+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-23T05:53:24.206+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:24.205+0000] {dag.py:2726} INFO - Creating ORM DAG for modelservice
[2023-04-23T05:53:24.232+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:24.232+0000] {dag.py:3456} INFO - Setting next_dagrun for modelservice to None, run_after=None
[2023-04-23T05:53:24.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 3.094 seconds
[2023-04-23T05:53:54.589+0000] {processor.py:153} INFO - Started process (PID=62) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T05:53:54.592+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T05:53:54.595+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:54.594+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T05:53:55.670+0000] {processor.py:753} INFO - DAG(s) dict_keys(['modelservice']) retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T05:53:55.695+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:55.695+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-23T05:53:55.712+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:53:55.712+0000] {dag.py:3456} INFO - Setting next_dagrun for modelservice to None, run_after=None
[2023-04-23T05:53:55.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 1.143 seconds
[2023-04-23T05:54:26.109+0000] {processor.py:153} INFO - Started process (PID=71) to work on /opt/airflow/dags/models_dags.py
[2023-04-23T05:54:26.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags.py for tasks to queue
[2023-04-23T05:54:26.113+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:54:26.113+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags.py
[2023-04-23T05:54:26.862+0000] {processor.py:753} INFO - DAG(s) dict_keys(['modelservice']) retrieved from /opt/airflow/dags/models_dags.py
[2023-04-23T05:54:26.887+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:54:26.887+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-23T05:54:26.903+0000] {logging_mixin.py:137} INFO - [2023-04-23T05:54:26.903+0000] {dag.py:3456} INFO - Setting next_dagrun for modelservice to None, run_after=None
[2023-04-23T05:54:26.914+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags.py took 0.811 seconds
